# Generated by Django 6.1.1 on 2026-09-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('tour', 'Music Tour'), ('brand', 'Brand Campaign'), ('film', 'Film & Media'), ('appearance', 'Public Appearance'), ('event', 'Corporate Event'), ('other', 'Other')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['-year', 'order'],
            },
        ),
    ]
