# Generated by Django 6.1.1 on 2026-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('role', models.CharField(help_text='e.g. Actress & Producer', max_length=120)),
                ('category', models.CharField(choices=[('actor', 'Actor / Actress'), ('musician', 'Musician'), ('athlete', 'Athlete'), ('influencer', 'Influencer'), ('presenter', 'TV Presenter'), ('comedian', 'Comedian'), ('other', 'Other')], default='actor', max_length=20)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='celebrities/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited Availability'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Celebrities',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
