# Generated by Django 6.1.1 on 2026-09-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebrities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('event_type', models.CharField(choices=[('corporate', 'Corporate Event'), ('private', 'Private Party'), ('wedding', 'Wedding'), ('concert', 'Concert / Performance'), ('brand', 'Brand Campaign'), ('appearance', 'Public Appearance'), ('virtual', 'Virtual Event'), ('other', 'Other')], max_length=20)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=200)),
                ('event_description', models.TextField(help_text='Describe your event and requirements')),
                ('budget', models.CharField(blank=True, help_text='Approximate budget range', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal team notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='celebrities.celebrity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
